#include "ObjectPool/K2Node/K2Node_SpawnObject.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "K2Node_MakeStruct.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "KismetCompiler.h"
#include "ObjectPool/ObjectPoolModuleStatics.h"
#include "ObjectPool/ObjectPoolModuleTypes.h"
#include "Parameter/ParameterModuleStatics.h"
#include "UObject/StructOnScope.h"
#include "UObject/UnrealType.h"

#define LOCTEXT_NAMESPACE "K2Node_SpawnObject"

namespace
{
	const FName SpawnClassPinName = TEXT("InClass");
	const FName SpawnParameterPinName = TEXT("InParameter");
}

void UK2Node_SpawnObject::AllocateDefaultPins()
{
	const UEdGraphSchema_K2* Schema = GetDefault<UEdGraphSchema_K2>();
	UClass* ResolvedClass = ObjectClass ? ObjectClass.Get() : UObject::StaticClass();

	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);
	UEdGraphPin* ClassPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Class, UObject::StaticClass(), SpawnClassPinName);
	ClassPin->DefaultObject = ResolvedClass;

	if(UScriptStruct* SpawnStruct = ResolveSpawnParameterStruct(); CanUseStruct(SpawnStruct))
	{
		FStructOnScope StructOnScope(SpawnStruct);
		for(TFieldIterator<FProperty> PropertyIt(SpawnStruct, EFieldIteratorFlags::IncludeSuper); PropertyIt; ++PropertyIt)
		{
			FProperty* Property = *PropertyIt;
			if(!Property->HasAllPropertyFlags(CPF_BlueprintVisible) ||
				Property->HasAnyPropertyFlags(CPF_BlueprintReadOnly | CPF_EditConst) || Property->ArrayDim > 1)
			{
				continue;
			}

			FEdGraphPinType PinType;
			if(!Schema->ConvertPropertyToPinType(Property, PinType))
			{
				continue;
			}

			UEdGraphPin* ParameterPin = CreatePin(EGPD_Input, PinType, Property->GetFName());
			ParameterPin->PinFriendlyName = Property->GetDisplayNameText();
			ParameterPin->bAdvancedView = Property->HasAnyPropertyFlags(CPF_AdvancedDisplay);
			ParameterPin->bDefaultValueIsIgnored = PinType.IsContainer();

			FString DefaultValue;
			if(FBlueprintEditorUtils::PropertyValueToString(Property, StructOnScope.GetStructMemory(), DefaultValue) &&
				Schema->IsPinDefaultValid(ParameterPin, DefaultValue, nullptr, FText::GetEmpty()).IsEmpty())
			{
				Schema->SetPinAutogeneratedDefaultValue(ParameterPin, DefaultValue);
			}
			else
			{
				Schema->SetPinAutogeneratedDefaultValueBasedOnType(ParameterPin);
			}
		}
	}

	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Object, ResolvedClass, UEdGraphSchema_K2::PN_ReturnValue);
}

void UK2Node_SpawnObject::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UScriptStruct* SpawnStruct = ResolveSpawnParameterStruct();
	if(!CanUseStruct(SpawnStruct))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingType", "@@ has no valid SpawnParameter type.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UK2Node_MakeStruct* MakeStructNode = CompilerContext.SpawnIntermediateNode<UK2Node_MakeStruct>(this, SourceGraph);
	MakeStructNode->StructType = SpawnStruct;
	MakeStructNode->bMadeAfterOverridePinRemoval = true;
	MakeStructNode->AllocateDefaultPins();
	CompilerContext.MessageLog.NotifyIntermediateObjectCreation(MakeStructNode, this);

	for(TFieldIterator<FProperty> PropertyIt(SpawnStruct, EFieldIteratorFlags::IncludeSuper); PropertyIt; ++PropertyIt)
	{
		if(UEdGraphPin* SourcePin = FindPin(PropertyIt->GetFName()))
		{
			if(UEdGraphPin* TargetPin = MakeStructNode->FindPin(PropertyIt->GetFName()))
			{
				CompilerContext.MovePinLinksToIntermediate(*SourcePin, *TargetPin);
			}
		}
	}

	UK2Node_CallFunction* MakeParameterNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	MakeParameterNode->SetFromFunction(UParameterModuleStatics::StaticClass()->FindFunctionByName(
		GET_FUNCTION_NAME_CHECKED(UParameterModuleStatics, MakeParameter)));
	MakeParameterNode->AllocateDefaultPins();
	UEdGraphPin* ValuePin = MakeParameterNode->FindPinChecked(TEXT("Value"));
	ValuePin->PinType.PinCategory = UEdGraphSchema_K2::PC_Struct;
	ValuePin->PinType.PinSubCategoryObject = SpawnStruct;
	MakeStructNode->FindPinChecked(SpawnStruct->GetFName())->MakeLinkTo(ValuePin);

	UK2Node_CallFunction* SpawnNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	SpawnNode->SetFromFunction(UObjectPoolModuleStatics::StaticClass()->FindFunctionByName(TEXT("SpawnObject")));
	SpawnNode->AllocateDefaultPins();
	SpawnNode->GetReturnValuePin()->PinType = GetResultPin()->PinType;

	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Execute), *SpawnNode->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *SpawnNode->GetThenPin());
	CompilerContext.MovePinLinksToIntermediate(*GetClassPin(), *SpawnNode->FindPinChecked(SpawnClassPinName));
	MakeParameterNode->GetReturnValuePin()->MakeLinkTo(SpawnNode->FindPinChecked(SpawnParameterPinName));
	CompilerContext.MovePinLinksToIntermediate(*GetResultPin(), *SpawnNode->GetReturnValuePin());
	BreakAllNodeLinks();
}

void UK2Node_SpawnObject::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	RefreshClassFromPin(Pin);
}

void UK2Node_SpawnObject::PinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::PinConnectionListChanged(Pin);
	RefreshClassFromPin(Pin);
}

FText UK2Node_SpawnObject::GetNodeTitle(ENodeTitleType::Type) const
{
	return ObjectClass && ObjectClass != UObject::StaticClass()
		? FText::Format(LOCTEXT("TypedNodeTitle", "Spawn Object ({0})"), ObjectClass->GetDisplayNameText())
		: LOCTEXT("NodeTitle", "Spawn Object");
}

FText UK2Node_SpawnObject::GetTooltipText() const
{
	return LOCTEXT("NodeTooltip", "Spawns or reuses an object and exposes the registered SpawnParameter fields.");
}

void UK2Node_SpawnObject::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* NodeClass = GetClass();
	if(ActionRegistrar.IsOpenForRegistration(NodeClass))
	{
		ActionRegistrar.AddBlueprintAction(NodeClass, UBlueprintNodeSpawner::Create(NodeClass));
	}
}

FText UK2Node_SpawnObject::GetMenuCategory() const
{
	return LOCTEXT("MenuCategory", "ObjectPoolModule");
}

bool UK2Node_SpawnObject::CanUseStruct(const UScriptStruct* Struct)
{
	return Struct && Struct != FSpawnParameter::StaticStruct() && Struct->IsChildOf(FSpawnParameter::StaticStruct()) &&
		!Struct->HasMetaData(TEXT("Abstract")) && !Struct->HasMetaData(TEXT("Deprecated")) &&
		!Struct->HasMetaData(TEXT("Hidden")) && !Struct->HasMetaData(TEXT("SpawnHidden"));
}

UClass* UK2Node_SpawnObject::ResolveObjectClass() const
{
	if(const UEdGraphPin* ClassPin = GetClassPin())
	{
		if(ClassPin->LinkedTo.Num() > 0)
		{
			if(UClass* LinkedClass = Cast<UClass>(ClassPin->LinkedTo[0]->PinType.PinSubCategoryObject.Get()))
			{
				return LinkedClass;
			}
		}
		if(UClass* DefaultClass = Cast<UClass>(ClassPin->DefaultObject))
		{
			return DefaultClass;
		}
	}
	return ObjectClass ? ObjectClass.Get() : UObject::StaticClass();
}

UScriptStruct* UK2Node_SpawnObject::ResolveSpawnParameterStruct() const
{
	return FObjectPoolSpawnParameterRegistry::Resolve(ResolveObjectClass());
}

UEdGraphPin* UK2Node_SpawnObject::GetClassPin() const
{
	return FindPin(SpawnClassPinName);
}

UEdGraphPin* UK2Node_SpawnObject::GetResultPin() const
{
	return FindPin(UEdGraphSchema_K2::PN_ReturnValue);
}

void UK2Node_SpawnObject::RefreshClassFromPin(UEdGraphPin* Pin)
{
	if(Pin != GetClassPin())
	{
		return;
	}

	UClass* NewClass = ResolveObjectClass();
	if(NewClass && NewClass != ObjectClass)
	{
		ObjectClass = NewClass;
		ReconstructNode();
	}
}

#undef LOCTEXT_NAMESPACE
